#!/usr/bin/env bash
# configures a brand new Ubuntu machine
# Nginx server so that /redirect_me is redirecting to another page.

echo -e "Updating and installing Nginx respectively.\n"
sudo apt-get update -y -qq
sudo apt-get install nginx -y

# to start nginx service
sudo service nginx start

# to allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# to give the user ownership to the website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# to backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# to creat new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# setting up /redirect_me to a youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?
v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# to restart nginx
sudo service nginx restart
