#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# contains the string Ceci n'est pas une page.
# Serve a page that would return a Hello World string

echo -e "Updating and installing Nginx respectively.\n"
sudo apt-get update -y -qq
sudo apt-get install nginx -y

# to start nginx service
sudo service nginx start

# to allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# to give ownership to website files for easy editing to the user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# to backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# to creat new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# to set up /redirect_me to a youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# to set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# to start nginx
sudo service nginx restart
